# Generated by Django 4.1.1 on 2022-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
