# Generated by Django 4.1.1 on 2022-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('TimeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
