# Generated by Django 4.1.1 on 2022-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
