# Generated by Django 4.1.1 on 2022-10-02 05:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Body',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
