# Generated by Django 4.1.1 on 2022-10-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Content',
        ),
    ]
