# Generated by Django 4.1.1 on 2022-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=100)),
                ('Issue', models.TextField()),
            ],
        ),
    ]
